include:
  - project: 'Cacophony/gitlab-ci'
    ref: master
    file: '/go-service.yml'
  - project: 'Cacophony/gitlab-ci'
    ref: master
    file: '/sentry.yml'

variables:
  DEPLOYMENT_NAME: "worker"

stages:
  - prepare
  - build
  - release
  - staging

Go Lint:
  stage: prepare
  extends: .Go Service - Go Lint

Docker Build:
  stage: build
  extends: .Go Service - Docker Build

Docker Release:
  stage: release
  extends: .Go Service - Docker Release

Sentry Release:
  stage: release
  extends: .Sentry - Sentry Release

Deploy Staging:
  stage: staging
  extends: .Go Service - Deploy Staging

Sentry Staging:
  stage: staging
  variables:
    SENTRY_ENV: "staging"
  extends: .Sentry - Sentry Deploy Staging
