# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/Seklfreak/ginside"

[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/slice"

[[constraint]]
  branch = "develop"
  name = "github.com/bwmarrin/discordgo"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.7.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.3"

[[constraint]]
  name = "github.com/mmcdole/gofeed"
  version = "1.0.0-beta2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "gitlab.com/Cacophony/SqsProcessor"

[[constraint]]
  branch = "master"
  name = "gitlab.com/Cacophony/dhelpers"

[prune]
  go-tests = true
  unused-packages = true
