apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
  namespace: cacophony
type: Opaque
stringData:
  discordTokens: "{{DISCORD_TOKENS}}"
  loggingDiscordWebhook: "{{LOGGING_DISCORD_WEBHOOK}}"
  dbDSN: "{{DB_DSN}}"
  redisPassword: "{{REDIS_PASSWORD}}"
  featureflagUnleashURL: "{{FEATUREFLAG_UNLEASH_URL}}"
  featureflagUnleashInstanceID: "{{FEATUREFLAG_UNLEASH_INSTANCE_ID}}"
  errortrackingRavenDSN: "{{ERRORTRACKING_RAVEN_DSN}}"
  instagramSessionIDs: "{{INSTAGRAM_SESSION_IDS}}"
  polrBaseURL: "{{POLR_BASE_URL}}"
  polrAPIKey: "{{POLR_API_KEY}}"
  amqpDSN: "{{AMQP_DSN}}"
  iexCloudAPISecret: "{{IEXCLOUD_API_SECRET}}"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      namespace: cacophony
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "registry.gitlab.com/cacophony/worker:{{DOCKER_IMAGE_HASH}}"
          readinessProbe:
            httpGet:
              path: /status
              port: {{PORT}}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: {{PORT}}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: PORT
              value: "{{PORT}}"
            - name: ENVIRONMENT
              value: "{{ENVIRONMENT}}"
            - name: REDIS_ADDRESS
              value: "{{REDIS_ADDRESS}}"
            - name: CLUSTER_ENVIRONMENT
              value: "{{CLUSTER_ENVIRONMENT}}"
            - name: HASH
              value: "{{HASH}}"
            - name: DISCORD_TOKENS
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: discordTokens
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: dbDSN
            - name: LOGGING_DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: loggingDiscordWebhook
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: redisPassword
            - name: FEATUREFLAG_UNLEASH_URL
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: featureflagUnleashURL
            - name: FEATUREFLAG_UNLEASH_INSTANCE_ID
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: featureflagUnleashInstanceID
            - name: ERRORTRACKING_RAVEN_DSN
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: errortrackingRavenDSN
            - name: INSTAGRAM_SESSION_IDS
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: instagramSessionIDs
            - name: POLR_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: polrBaseURL
            - name: POLR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: polrAPIKey
            - name: AMQP_DSN
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: amqpDSN
            - name: IEXCLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: processor-secret
                  key: iexCloudAPISecret


---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: worker
